[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

[[redirects]]
  from = "/api/*"
  to = "https://td-server-bookstore.herokuapp.com/api/:splat"
  status = 200
  force = false
