pull_request_rules:
  - name: Automated merge for Renovate pull requests
    conditions:
      - author=renovate[bot]
      - status-success=server-build (14.x)
      - status-success=server-unit-tests (14.x)
      - status-success=server-e2e-tests (14.x)
      - status-success=client-build (14.x)
      - status-success=client-unit-tests (14.x)
      - status-success=server-lint (14.x)
      - status-success=client-lint (14.x)
    actions:
      merge:
        method: merge
      label:
        add: ['chore(deps):', '🛠 Improvement']

  - name: Automated dependabot merge
    conditions:
      - author~=^dependabot(|-preview)\[bot\]$
      - status-success=server-build (14.x)
      - status-success=server-unit-tests (14.x)
      - status-success=server-e2e-tests (14.x)
      - status-success=client-build (14.x)
      - status-success=client-unit-tests (14.x)
      - status-success=server-lint (14.x)
      - status-success=client-lint (14.x)
    actions:
      merge:
        method: merge
      label:
        add: ['chore(deps):', '🛠 Improvement']
