name: Server lint

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  server-lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        working-directory: ./server
        run: yarn install

      - name: Run linter
        working-directory: ./server
        run: yarn lint

